"""facility add icon

Revision ID: ed6742a5f832
Revises: c84ee1eb70ce
Create Date: 2020-06-23 14:47:01.421637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6742a5f832'
down_revision = 'c84ee1eb70ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_facility_info', sa.Column('icon', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ih_facility_info', 'icon')
    # ### end Alembic commands ###
